---
layout: page
title: Golang func
category: blog
description: 
date: 2018-09-27
---
# define func
1. 不支持嵌套nested, 重载overload 和 
2. 不支持默认参数default parameter
3. 支持不定长变参数
4. 多返回值
5. 支持命名返回参数
6. 支持匿名函数和闭包

## Function Closures
https://stackoverflow.com/questions/21961615/why-doesnt-go-allow-nested-function-declarations-functions-inside-functions

直接定义inner function(nested) 是不行的, 除了匿名函数随便生成：

    inc := func(x int) int { return x+1; }
    return func(x int) int { return x+1; }

A closure example

	func adder() func(int) int {
		sum := 0
		return func(x int) int {
			sum += x
			return sum
		}
	}

	func main() {
		pos, neg := adder(), adder()
		for i := 0; i < 10; i++ {
			fmt.Println(
				pos(i),
				neg(-2*i),
			)
		}
	}

### 匿名函数是变量funcVal 对象
    // --- func as slice ----
    fns := [](func(x int) int){
        func(x int) int { return x + 1 },
        func(x int) int { return x + 2 },
    }
    fns[0](100)


    // --- function as field ---
    d := struct {
        fn func() string
    }{
        fn: func() string { return "Hello, World!" },
    }
    println(d.fn())

    // --- channel of function ---
    fc := make(chan func() string, 2)
    fc <- func() string { return "Hello, World!" }
    println((<-fc)())

闭包复制的是原对象指针，这就很容易解释延迟引⽤用现象。

    //x 不会被回收, 它属于回调函数的空间
    func test() func() {
        x := 100
        fmt.Printf("x (%p) = %d\n", &x, x)
        return func() {
            fmt.Printf("x (%p) = %d\n", &x, x)
    } 
    func main() {
        f := test()
        // x 是闭包引用过来的
        f() 
    }

匿名函数实际上在汇编层FuncVal 对象, 其中包含了匿名函数地址、闭包对象指 针。当调⽤用匿名函数时，只需以某个寄存器传递该对象即可。

    FuncVal { func_address, closure_var_pointer ... }

## multi Parameters(变参)
变参其实是一个slice: []int

	func sum(nums ...int) {
	    fmt.Printf("%T",nums)  //slice = []int{1, 2, 3)
	}
    s:=[]int{1,2,3}
	sum(s...)
	sum(1, 2, 3)

any type: interface{} , `$ godoc fmt Printf`

	func Statusln(a ...interface{})
	a := []interface{}{"hello", "world", 42}

## Multiple results
A function can return any number of results.

	func swap(x, y string) (string, string) {
		return y, x
	}
	a, b := swap("hello", "world")
	a, _ := swap("hello", "world")

multi return 不能赋值为单值，但是可以传给变参

    // error
	a := swap("hello", "world")

    func(x,y string){
        println(x,y)
    }(swap("a","b"))

    func(args ...string){
        println(args[0],args[1])
    }(swap("a","b"))

传多值时，就不能变参与形参混用了, 报: multiple-value in sigle-value context error
不传多值时，就可以混用

    func(z int,x,y string){
        println(z,x,y)
    }(swap(1, "a","b"))

    func(z int, args ...string){
        println(z, args[0],args[1])
    }(swap(2, "a","b"))



### Named return values
A return statement `without` arguments returns the `named return values`.

	func split(sum int) (x, y int) {
		x = sum * 4 / 9
		y = sum - x
		return
	}
    x,y:=split(17)
	fmt.Println(split(17))

Named value redeclared error:

    func add(x, y int) (z int) { 
        var z=x+y   //z redeclared
        return z
    }
    func main() {
        println(add(1, 2))
    }

### defer 修改返回值
    func add(x, y int) (z int) {
        defer func() { z += 100 }()
        z=x+y
        return 
    }
    func main() {
        println(add(1, 2))
    }

或者return 直接修改：

    func add(x, y int) (z int) {
        defer func() {
            println(z) // 输出: 203
        }()
        z=x+y return z + 200
    }
    func main() {
        println(add(1, 2)) // 执⾏行顺序: (z = z + 200) -> (call defer) -> (ret)
    }


## func is value
    func test(fn func() int) int {
        return fn()
    }
    type FormatFunc func(s string, x, y int) string // 定义函数类型。
    func format(fn FormatFunc, s string, x, y int) string {
        return fn(s, x, y)
    }
    func main() {
        s1 := test(func() int { return 100 })
        s2 := format(func(s string, x, y int) string {
            return fmt.Sprintf(s, x, y)
        }, "%d, %d", 10, 20)
        println(s1, s2)
    }

# Methods(struct)
Go does not have classes. However, you can define methods with a special receiver argument.
The receiver appears in its `own argument list` between the `func keyword` and the `method name`.

	type Vertex struct {
		X, Y float64
	}

	func (v Vertex) Abs() float64 {
		return math.Sqrt(v.X*v.X + v.Y*v.Y)
	}

	func main() {
		v := Vertex{3, 4}
		fmt.Println(v.Abs())
	}

## Mehtond on local-type
Declare a method on non-struct types, such as float64

	type MyFloat float64

	func (f MyFloat) Abs() float64 {
		if f < 0 {
			return float64(-f)
		}
		return float64(f)
	}

	func main() {
		f := MyFloat(-math.Sqrt2)
		fmt.Println(f.Abs())
	}

You can only declare:
1. a method with a receiver whose **type** is **defined in the same package** as the method.
2. You cannot declare a method with a receiver whose type is defined in another package (such as the built-in types: int float64).

## methods with pointer receivers.
If you wanna change receivers, use pointer pls.

	type Vertex struct {
		X, Y float64
	}

	func (v Vertex) Abs() float64 {
		return math.Sqrt(v.X*v.X + v.Y*v.Y)
	}

    // Pointer 指针，而不是copy
	func (v *Vertex) Scale(f float64) {
		v.X = v.X * f
		v.Y = v.Y * f
	}

	func main() {
		v := Vertex{3, 4}
		v.Scale(10)
		fmt.Println(v.Abs())
	}

### pointer as arg
the method call `p.Abs()` is interpreted as `(*p).Abs()`.

	var v Vertex
	fmt.Println(v.Abs()) // OK
	p := &v
	fmt.Println(p.Abs()) // OK interpreted as `(*p).Abs()`.

# Errors
The error type is a built-in interface similar to fmt.Stringer:
error类型本身就是一个预定义好的接口，里面定义了一个method

	type error interface {
	    Error() string
	}

	nil
	io.EOF

## 方式1：errrors.New

    import "errors"
    func main() {
        var err error = errors.New("this is a new error")
        var EOF = errors.New("EOF")
        fmt.Println(EOF.Error(), err.Error())
        fmt.Println(EOF, err)

    }

## 方式2： fmt.Errorf
    err = fmt.Errorf("%s", "the error test for fmt.Errorf")
    fmt.Println(err.Error())

## custom MyError
方式3: 自定义Customeror 结构体和Error(): 

	type MyError struct {
		When time.Time
		What string
	}

	func (e *MyError) Error() string {
		return fmt.Sprintf("at %v, %s",
			e.When, e.What)
	}

	func run() (string, error) {
		return "results!!", &MyError{
			time.Now(),
			"it didn't work",
		}
	}

	func main() {
		if ret, err := run(); err != nil {
			fmt.Println(ret,err)
		}
	}

# defer 延迟调用
    func test() error {
        f, err := os.Create("test.txt")
        if err != nil { return err }
        defer f.Close()
        f.WriteString("Hello, World!")
        return nil 
    }

多个defer 遵守FIFO 规则，在调用返回ret 前执行

    func test(x int) {
        defer println("a")
        defer println("b")
        defer func() {
            println(100 / x) // div0 异常未被捕获，逐步往外传递，最终终⽌止进程。
        }()
        defer println("c")
    }
    func main() {
        test(0)
    }

    // output:
    c
    b
    a
    panic: runtime error: integer divide by zero

## Panic
相当于 php 的 die, 但是可以通过 defer 被 recovery 捕获:

	func g(i int) {
		 fmt.Println("Panic!")
		 panic(fmt.Sprintf("%v", i))
	}

	func f() {
		 defer func() {
				 if r := recover(); r != nil {
						 fmt.Println("Recovered in f", r)
				 }
		 }()

		i := 10
		fmt.Println("Calling g with ", i)
		g(i)
		fmt.Println("Returned normally from g.")
	}

### multi panic 
只有最后一个被捕获

    func test() {
        defer func() {
            fmt.Println(recover())
        }()
        defer func() {
            panic("defer panic")
    }()
        panic("test panic")
    }
    func main() {
        test()
    }
    输出:
    defer panic

## recover
由于 panic、recover 参数类型为 interface{}，因此可抛出任何类型对象。

    func panic(v interface{})
    func recover() interface{}

recover 只有在延迟`函数调⽤`内直接调⽤用才会终⽌止错误，否则总是返回 nil
以下三者都返回的nil

    defer recover()
    defer fmt.Println(recover())
    defer func() {
        func() {
            println("defer inner")
            recover()
        }()
    }()

返回panic 

    defer func() {
        println("defer inner")
        recover()
    }()
    defer func() {
        if err := recover(); err != nil {
            println(err.(string))
        }
    }
    panic("panic error!")